name: Updated

on:
  workflow_dispatch:

jobs:
  all:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: Build docker image
      run: docker build --tag ppag-planejamento .
    - name: ETL pipeline
      run: docker run --rm --mount type=bind,source=${PWD},target=/project ppag-planejamento make all
    - name: Publish data package
      run: make publish
